---
title: "Hands-on Exercise 1:Geospatial Data Wrangling with R"
editor: visual
---

Overview

This is Geospatial Data Wrangling with R.

Getting Started

The code chunk below will install and load tidyverse and sf packages.

```{r}
pacman::p_load(sf,tidyverse)

```

Importing Geospatial Data

Importing polygon features

This code chunk wil import ESPI shapefile into R.

```{R}
mpsz <- st_read(dsn = "data/geospatial/", layer = "MP14_SUBZONE_WEB_PL")

```

Importing polyline feature data in shapefile form.

```{R}
cyclingpath = st_read(dsn = "data/geospatial", 
                         layer = "CyclingPathGazette")
```

Importing GIS data in kml format.

```{R}
preschool = st_read("data/geospatial/pre-schools-location-kml.kml")

```

Working with st_geometry()

```{R}
st_geometry(mpsz)
```

Working with glimpse()

```{R}
glimpse(mpsz)
```

Working with head()

```{R}
head(mpsz, n=5)
```

Plotting the Geospatial Data

```{R}
plot(mpsz)
plot(st_geometry(mpsz))
plot(mpsz["PLN_AREA_N"])
```

Working with Projection

```{R}
st_crs(mpsz)
mpsz3414 <- st_set_crs(mpsz, 3414)
st_crs(mpsz3414)
```

Transforming the projection of preschool from wgs84 to svy21.

```{R}
preschool3414 <- st_transform(preschool, 
                              crs = 3414)
```

Importing and Converting An Aspatial Data Importing the aspatial data

```{R}
listings <- read_csv("data/aspatial/listings.csv")
list(listings) 
```

Creating a simple feature data frame from an aspatial data frame

```{R}
listings_sf <- st_as_sf(listings, 
                       coords = c("longitude", "latitude"),
                       crs=4326) %>%
  st_transform(crs = 3414)
glimpse(listings_sf)
```

Geoprocessing with sf package Buffering

```{R}
buffer_cycling <- st_buffer(cyclingpath, 
                               dist=5, nQuadSegs = 30)
buffer_cycling$AREA <- st_area(buffer_cycling)
sum(buffer_cycling$AREA)
```

Point-in-polygon count

```{R}
mpsz3414$`PreSch Count`<- lengths(st_intersects(mpsz3414, preschool3414))
summary(mpsz3414$`PreSch Count`)
top_n(mpsz3414, 1, `PreSch Count`)
mpsz3414$Area <- mpsz3414 %>%
  st_area()
mpsz3414 <- mpsz3414 %>%
  mutate(`PreSch Density` = `PreSch Count`/Area * 1000000)
```

Explorotary Data Analysis (EDA)

```{R}
hist(mpsz3414$`PreSch Density`)
ggplot(data=mpsz3414, 
       aes(x= as.numeric(`PreSch Density`)))+
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue") +
  labs(title = "Are pre-school even distributed in Singapore?",
       subtitle= "There are many planning sub-zones with a single pre-school, on the other hand, \nthere are two planning sub-zones with at least 20 pre-schools",
      x = "Pre-school density (per km sq)",
      y = "Frequency")

plot(mpsz3414$`PreSch Density`,mpsz3414$`PreSch Count`,main="Pre-school Density VS Pre-school Count", xlab = "Density", ylab ="Count")
```
